---
# GitHub runner role defaults
github_runner:
  enabled: true
  version: "latest"
  work_dir: "{{ ansible_env.HOME }}/.iac-toolbox/github-runner"
  labels: "self-hosted,ARM64"
  repo_url: ""
  token: ""
