import fs from 'fs/promises';
import path from 'path';
import type { GitHubBuildWorkflowConfig } from '../components/GitHubBuildWorkflowDialog.js';

interface IacToolboxYamlConfig {
  selectedIntegrations: string[];
  githubBuildWorkflow?: GitHubBuildWorkflowConfig;
}

/**
 * Generate the contents of iac-toolbox.yml.
 *
 * All integrations are represented in the output regardless of selection.
 * Disabled integrations default to `enabled: false` with a "coming soon" comment.
 * Sensitive values are replaced with variable references.
 */
export function generateIacToolboxYaml(config: IacToolboxYamlConfig): string {
  const lines: string[] = [
    '# Generated by iac-toolbox init',
    '# Safe to commit — no secrets stored here',
    '',
    'docker:',
    '  enabled: true # always installed, not configurable',
    '',
  ];

  // GitHub Build Workflow
  if (config.selectedIntegrations.includes('github_build_workflow') && config.githubBuildWorkflow) {
    lines.push('github_build_workflow:');
    lines.push('  enabled: true');
    lines.push(`  docker_hub_username: "${config.githubBuildWorkflow.dockerHubUsername}"`);
    lines.push(`  docker_image_name: "${config.githubBuildWorkflow.dockerImageName}"`);
    lines.push('  docker_hub_token: "{{ docker_hub_token }}" # injected by CLI at deploy time');
  } else {
    lines.push('github_build_workflow:');
    lines.push('  enabled: false');
  }

  // Coming soon integrations — always disabled
  lines.push('');
  lines.push('github_runner:');
  lines.push('  enabled: false # coming soon');
  lines.push('');
  lines.push('cloudflare:');
  lines.push('  enabled: false # coming soon');
  lines.push('');
  lines.push('vault:');
  lines.push('  enabled: false # coming soon');
  lines.push('');
  lines.push('grafana:');
  lines.push('  enabled: false # coming soon');
  lines.push('');
  lines.push('pagerduty:');
  lines.push('  enabled: false # coming soon');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write iac-toolbox.yml to the specified directory.
 */
export async function writeIacToolboxYaml(
  directory: string,
  config: IacToolboxYamlConfig,
): Promise<string> {
  const content = generateIacToolboxYaml(config);
  const filePath = path.join(directory, 'iac-toolbox.yml');
  await fs.writeFile(filePath, content, 'utf-8');
  return filePath;
}

export type { IacToolboxYamlConfig };
